import { supabase } from '../lib/supabase';
import type { NfcCard, NfcStatus } from '../types/database';

export interface NfcCardListItem extends NfcCard {
  business_name: string | null;
}

export async function listNfcCards(): Promise<NfcCardListItem[]> {
  const { data, error } = await supabase
    .from('nfc_cards')
    .select('*, businesses(name)')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data as any[]).map((c) => ({ ...c, business_name: c.businesses?.name ?? null }));
}

/** card_code is auto-generated by the DB default (generate_card_code()). */
export async function createNfcCard(): Promise<NfcCard> {
  const { data, error } = await supabase.from('nfc_cards').insert({}).select().single();
  if (error) throw error;
  return data as NfcCard;
}

export async function assignNfcCard(cardId: string, businessId: string): Promise<NfcCard> {
  // Guard against assigning a card that's already actively linked elsewhere —
  // the UI should confirm re-linking, but the update itself is what matters.
  const { data, error } = await supabase
    .from('nfc_cards')
    .update({ business_id: businessId, status: 'active', assigned_at: new Date().toISOString() })
    .eq('id', cardId)
    .select()
    .single();
  if (error) throw error;
  return data as NfcCard;
}

export async function unassignNfcCard(cardId: string): Promise<NfcCard> {
  const { data, error } = await supabase
    .from('nfc_cards')
    .update({ business_id: null, status: 'available', assigned_at: null })
    .eq('id', cardId)
    .select()
    .single();
  if (error) throw error;
  return data as NfcCard;
}

export async function setNfcStatus(cardId: string, status: NfcStatus): Promise<NfcCard> {
  const { data, error } = await supabase.from('nfc_cards').update({ status }).eq('id', cardId).select().single();
  if (error) throw error;
  return data as NfcCard;
}
